env:
  es2021: true
  node: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  require-jsdoc: off,
  "indent": [ 2, "tab" ],
  "no-mixed-spaces-and-tabs": [2, "smart-tabs"],
  "max-len": [2, 200],
  "no-tabs": off,
  "new-cap": off,
}